services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    # shm_size maybe not needed
    shm_size: 128mb
    # Ports can be adjusted as wished
    ports:
      - "30090:5432"
    # Change Postgres password if you are in Production
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
